FILE: requirements.txt
```txt
streamlit
pandas
openpyxl
plotly
python-dotenv
```

FILE: .env
```
APP_TITLE="AI Agent Workbench"
LOG_LEVEL="INFO"
```

FILE: README.md
```md
# AI Agent Workbench

A lightweight and extensible Streamlit frontend foundation for AI agent interaction, data exploration, and future development.

## Project Structure

*   `ai_agent_streamlit_app/` (root directory)
    *   `app.py`: Main Streamlit application entry point.
    *   `requirements.txt`: Python dependencies.
    *   `.env`: Environment variables for configuration.
    *   `README.md`: This documentation.
    *   `utils/`:
        *   `config.py`: Configuration loading.
        *   `data_loader.py`: Handles data file uploads (CSV, Excel).
        *   `plotter.py`: Generates interactive charts using Plotly.
    *   `data/`:
        *   `sample_sales.csv`: Sample dataset.
        *   `sample_users.xlsx`: Sample dataset (generated by `create_sample_excel.py`).
        *   `create_sample_excel.py`: Script to generate `sample_users.xlsx`.
    *   `logs/`: Application log files.

## Setup and Installation

Follow these steps to get the application running locally:

1.  **Clone the Repository (if applicable) or Create Project Structure:**
    If you received these files as a zipped project, simply navigate into the `ai_agent_streamlit_app/` directory.
    If you're creating from scratch, make sure your directory structure matches the "Project Structure" above, especially `utils/`, `data/`, and `logs/`.

2.  **Create a Virtual Environment:**
    It's highly recommended to use a virtual environment to manage dependencies.
    ```bash
    python -m venv .venv
    ```

3.  **Activate the Virtual Environment:**
    *   **On macOS/Linux:**
        ```bash
        source .venv/bin/activate
        ```
    *   **On Windows:**
        ```bash
        .venv\Scripts\activate
        ```

4.  **Install Dependencies:**
    ```bash
    pip install -r requirements.txt
    ```

5.  **Generate Sample Data (Excel file):**
    The `data/sample_users.xlsx` file needs to be generated. Navigate to the root of the project and run the provided script:
    ```bash
    python data/create_sample_excel.py
    ```
    This will create `sample_users.xlsx` in the `data/` directory.

## Running the Application

Once setup is complete, you can run the Streamlit application:

```bash
streamlit run app.py
```

Your browser should automatically open to the application, typically at `http://localhost:8501`.

## Usage

1.  **Home Page:** Provides a welcome message and an overview.
2.  **Data Explorer:**
    *   **Upload Data:** Use the file uploader to select a CSV or Excel (`.xlsx`) file.
    *   **Data Preview:** The first few rows of your uploaded data will be displayed.
    *   **Chart Generation:**
        *   Select a `Chart Type` (Bar, Line, Pie, Scatter).
        *   Select `X-axis`, `Y-axis`, and an optional `Color/Group by` column from your dataset.
        *   Click `Generate Chart` to visualize your data.
3.  **AI Agent Playground:** A placeholder section for future AI agent integration.

## Configuration

The application loads configuration from the `.env` file at the root of the project. You can modify these variables:

*   `APP_TITLE`: The title displayed in the Streamlit app's browser tab and main header.
*   `LOG_LEVEL`: Controls the verbosity of application logging (e.g., `INFO`, `DEBUG`, `WARNING`, `ERROR`).

## Logging

Application logs are written to `logs/app.log` and also output to the console.

---
```

FILE: utils/config.py
```python
import os
from dotenv import load_dotenv

def load_config():
    """
    Loads configuration from environment variables, preferring values from .env file.
    """
    load_dotenv() # take environment variables from .env.
    return {
        "APP_TITLE": os.getenv("APP_TITLE", "AI Agent Workbench"),
        "LOG_LEVEL": os.getenv("LOG_LEVEL", "INFO"),
    }
```

FILE: utils/data_loader.py
```python
import pandas as pd
import streamlit as st
import io

def load_data(uploaded_file: st.UploadedFile) -> pd.DataFrame | None:
    """
    Loads data from an uploaded file (CSV or Excel) into a pandas DataFrame.

    Args:
        uploaded_file: The file uploaded via Streamlit's st.file_uploader.

    Returns:
        A pandas DataFrame if the file is successfully loaded, None otherwise.
    """
    if uploaded_file is None:
        return None

    file_extension = uploaded_file.name.split('.')[-1].lower()

    try:
        if file_extension == 'csv':
            df = pd.read_csv(uploaded_file)
        elif file_extension in ['xlsx', 'xls']:
            df = pd.read_excel(uploaded_file)
        else:
            st.error(f"Unsupported file type: .{file_extension}. Please upload a CSV or Excel file.")
            return None
        return df
    except Exception as e:
        st.error(f"Error loading file: {e}")
        return None
```

FILE: utils/plotter.py
```python
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

def generate_chart(df: pd.DataFrame, chart_type: str, x_col: str, y_col: str = None, color_col: str = None) -> go.Figure | None:
    """
    Generates a Plotly chart based on the selected type and columns.

    Args:
        df: The pandas DataFrame containing the data.
        chart_type: The type of chart to generate (e.g., "Bar Chart", "Line Chart").
        x_col: The column to use for the X-axis.
        y_col: The column to use for the Y-axis (optional, required for some charts).
        color_col: The column to use for coloring/grouping (optional).

    Returns:
        A Plotly Figure object if successful, None otherwise.
    """
    if df.empty:
        st.warning("Cannot generate chart from empty data.")
        return None

    try:
        if chart_type == "Bar Chart":
            if y_col:
                # Ensure y_col is numeric for plotting
                df[y_col] = pd.to_numeric(df[y_col], errors='coerce')
                # Drop rows where y_col became NaN due to coercion
                df_filtered = df.dropna(subset=[y_col])
                if df_filtered.empty:
                    st.warning(f"No numeric data in '{y_col}' after cleaning. Cannot create bar chart.")
                    return None
                fig = px.bar(df_filtered, x=x_col, y=y_col, color=color_col, title=f"{y_col} by {x_col}")
            else:
                st.warning("Y-axis is required for Bar Chart.")
                return None
        elif chart_type == "Line Chart":
            if y_col:
                # Ensure x_col is suitable for line chart (numeric or datetime)
                # Attempt to convert x_col to datetime if possible
                try:
                    df[x_col] = pd.to_datetime(df[x_col], errors='coerce')
                    df_filtered = df.dropna(subset=[x_col])
                    if df_filtered.empty:
                        st.warning(f"No valid date/time data in '{x_col}' after cleaning. Cannot create line chart.")
                        return None
                except Exception:
                    # If not datetime, ensure it's numeric for a numeric line plot
                    df[x_col] = pd.to_numeric(df[x_col], errors='coerce')
                    df_filtered = df.dropna(subset=[x_col])
                    if df_filtered.empty:
                        st.warning(f"No numeric data in '{x_col}' after cleaning. Cannot create line chart.")
                        return None

                # Ensure y_col is numeric for plotting
                df_filtered[y_col] = pd.to_numeric(df_filtered[y_col], errors='coerce')
                df_filtered = df_filtered.dropna(subset=[y_col])
                if df_filtered.empty:
                    st.warning(f"No numeric data in '{y_col}' after cleaning. Cannot create line chart.")
                    return None

                fig = px.line(df_filtered, x=x_col, y=y_col, color=color_col, title=f"{y_col} over {x_col}")
            else:
                st.warning("Y-axis is required for Line Chart.")
                return None
        elif chart_type == "Pie Chart":
            if x_col: # x_col will be used as 'names' and y_col as 'values'
                if y_col:
                    # Ensure y_col is numeric for values
                    df[y_col] = pd.to_numeric(df[y_col], errors='coerce')
                    df_filtered = df.dropna(subset=[y_col])
                    if df_filtered.empty:
                        st.warning(f"No numeric data in '{y_col}' after cleaning. Cannot create pie chart.")
                        return None
                    fig = px.pie(df_filtered, names=x_col, values=y_col, title=f"Distribution of {y_col} by {x_col}")
                else:
                    st.warning("Y-axis is required for Pie Chart values.")
                    return None
            else:
                st.warning("X-axis (for names) is required for Pie Chart.")
                return None
        elif chart_type == "Scatter Plot":
            if x_col and y_col:
                # Ensure x_col and y_col are numeric for plotting
                df[x_col] = pd.to_numeric(df[x_col], errors='coerce')
                df[y_col] = pd.to_numeric(df[y_col], errors='coerce')
                df_filtered = df.dropna(subset=[x_col, y_col])
                if df_filtered.empty:
                    st.warning(f"No numeric data in '{x_col}' or '{y_col}' after cleaning. Cannot create scatter plot.")
                    return None
                fig = px.scatter(df_filtered, x=x_col, y=y_col, color=color_col, title=f"Scatter Plot of {y_col} vs {x_col}")
            else:
                st.warning("X-axis and Y-axis are required for Scatter Plot.")
                return None
        else:
            st.warning("Unsupported chart type selected.")
            return None

        return fig
    except Exception as e:
        st.error(f"Error generating chart: {e}")
        return None
```

FILE: data/sample_sales.csv
```csv
Date,Region,Product,Sales,Units
2023-01-01,East,Laptop,1200,5
2023-01-02,West,Mouse,25,10
2023-01-03,North,Keyboard,75,3
2023-01-04,South,Monitor,300,2
2023-01-05,East,Laptop,1500,6
2023-01-06,West,Keyboard,80,4
2023-01-07,North,Mouse,30,12
2023-01-08,South,Monitor,450,3
2023-01-09,East,Mouse,20,8
2023-01-10,West,Laptop,1100,4
2023-01-11,North,Monitor,350,2
2023-01-12,South,Keyboard,60,2
2023-01-13,East,Keyboard,90,3
2023-01-14,West,Monitor,280,2
2023-01-15,North,Laptop,1300,5
```

FILE: data/create_sample_excel.py
```python
import pandas as pd
import os
from datetime import datetime, timedelta

def create_sample_excel_file():
    """
    Creates a sample 'sample_users.xlsx' file in the 'data' directory.
    """
    data_dir = os.path.join(os.path.dirname(__file__))
    os.makedirs(data_dir, exist_ok=True) # Ensure data directory exists

    file_path = os.path.join(data_dir, 'sample_users.xlsx')

    # Generate sample data
    num_users = 10
    users_data = {
        'User ID': [f'U{i:03d}' for i in range(1, num_users + 1)],
        'Name': [f'User {i}' for i in range(1, num_users + 1)],
        'Age': [20 + i % 40 for i in range(num_users)],
        'Registration Date': [(datetime(2022, 1, 1) + timedelta(days=i*7)).strftime('%Y-%m-%d') for i in range(num_users)],
        'Active': [True if i % 2 == 0 else False for i in range(num_users)],
        'Country': ['USA', 'Canada', 'UK', 'Germany', 'France'] * (num_users // 5) + ['USA'] * (num_users % 5)
    }

    df = pd.DataFrame(users_data)

    try:
        df.to_excel(file_path, index=False)
        print(f"Successfully created sample Excel file: {file_path}")
    except Exception as e:
        print(f"Error creating sample Excel file: {e}")

if __name__ == "__main__":
    create_sample_excel_file()
```

FILE: app.py
```python
import streamlit as st
import pandas as pd
import logging
import os
from datetime import datetime

# Import local utilities
from utils.config import load_config
from utils.data_loader import load_data
from utils.plotter import generate_chart

# --- Configuration and Logging Setup ---
config = load_config()
APP_TITLE = config["APP_TITLE"]
LOG_LEVEL_STR = config["LOG_LEVEL"].upper()

# Ensure logs directory exists
log_dir = "logs"
os.makedirs(log_dir, exist_ok=True)

# Map string log levels to logging module constants
LOG_LEVEL = getattr(logging, LOG_LEVEL_STR, logging.INFO)

# Setup logging
logging.basicConfig(
    level=LOG_LEVEL,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(os.path.join(log_dir, 'app.log')),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

logger.info(f"Application started with title: {APP_TITLE} and log level: {LOG_LEVEL_STR}")

# --- Streamlit Page Configuration ---
st.set_page_config(
    page_title=APP_TITLE,
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- Initialize Session State ---
if 'uploaded_df' not in st.session_state:
    st.session_state['uploaded_df'] = pd.DataFrame()
    logger.debug("Initialized 'uploaded_df' in session state.")

# --- Sidebar Navigation ---
st.sidebar.title("Navigation")
page = st.sidebar.radio("Go to", ["Home", "Data Explorer", "AI Agent Playground"])

# --- Main Content Area ---
st.title(APP_TITLE)

if page == "Home":
    st.header("Welcome to the AI Agent Workbench!")
    st.markdown("""
        This platform serves as a versatile frontend foundation for interacting with AI agents,
        exploring datasets, and developing new AI-powered features.

        Use the sidebar to navigate:
        - **Data Explorer:** Upload and visualize your data with interactive charts.
        - **AI Agent Playground:** A dedicated space for future AI agent interactions and experiments.
    """)
    logger.info("Accessed Home page.")

elif page == "Data Explorer":
    st.header("Data Explorer")
    st.markdown("Upload a CSV or Excel file to preview your data and generate interactive charts.")

    uploaded_file = st.file_uploader("Choose a CSV or Excel file", type=["csv", "xlsx", "xls"])

    if uploaded_file is not None:
        logger.info(f"File uploaded: {uploaded_file.name}")
        df = load_data(uploaded_file)
        if df is not None:
            st.session_state['uploaded_df'] = df
            st.success("File successfully loaded!")
            logger.info(f"Loaded DataFrame shape: {df.shape}")
        else:
            st.session_state['uploaded_df'] = pd.DataFrame() # Clear df on error
            st.error("Could not load the file. Please check its format.")
            logger.error(f"Failed to load file: {uploaded_file.name}")

    df_to_display = st.session_state.get('uploaded_df', pd.DataFrame())

    if not df_to_display.empty:
        st.subheader("Data Preview")
        st.dataframe(df_to_display.head())
        st.write(f"Showing first {min(5, len(df_to_display))} rows of {len(df_to_display)} rows and {len(df_to_display.columns)} columns.")

        st.subheader("Chart Generator")
        all_columns = df_to_display.columns.tolist()

        if not all_columns:
            st.warning("No columns available to generate charts.")
            logger.warning("No columns in DataFrame for chart generation.")
        else:
            col1, col2, col3 = st.columns(3)

            with col1:
                chart_type = st.selectbox(
                    "Select Chart Type",
                    ("Bar Chart", "Line Chart", "Pie Chart", "Scatter Plot"),
                    key="chart_type"
                )
            with col2:
                x_col = st.selectbox(
                    "Select X-axis Column",
                    options=[''] + all_columns,
                    index=0,
                    key="x_axis_col"
                )
            with col3:
                y_col = st.selectbox(
                    "Select Y-axis Column",
                    options=[''] + all_columns,
                    index=0,
                    key="y_axis_col"
                )

            color_col = st.selectbox(
                "Optional: Color/Group by Column",
                options=[''] + all_columns,
                index=0,
                key="color_col"
            )

            # Filter out empty selections
            x_col_final = x_col if x_col != '' else None
            y_col_final = y_col if y_col != '' else None
            color_col_final = color_col if color_col != '' else None

            if st.button("Generate Chart"):
                logger.info(f"Attempting to generate {chart_type} with x={x_col_final}, y={y_col_final}, color={color_col_final}")
                if x_col_final is None:
                    st.warning("Please select at least an X-axis column to generate a chart.")
                else:
                    try:
                        # Attempt to generate chart using plotter utility
                        fig = generate_chart(df_to_display.copy(), chart_type, x_col_final, y_col_final, color_col_final)
                        if fig:
                            st.plotly_chart(fig, use_container_width=True)
                            logger.info(f"Successfully generated {chart_type}.")
                        else:
                            st.warning("Chart could not be generated with the selected options. Please check your column selections and data types.")
                            logger.warning(f"Failed to generate {chart_type} due to plotter returning None. Check previous warnings.")
                    except Exception as e:
                        st.error(f"An unexpected error occurred during chart generation: {e}")
                        logger.exception("Unexpected error during chart generation.")
    else:
        st.info("Upload a file above to begin data exploration.")

elif page == "AI Agent Playground":
    st.header("AI Agent Playground (Coming Soon!)")
    st.markdown("""
        This section is reserved for future enhancements where you will be able to
        interact directly with various AI agents.

        Potential features include:
        - Natural language querying of your uploaded data.
        - Automated report generation.
        - Interactive data transformations through conversational AI.
        - Integration with large language models for complex tasks.
    """)
    logger.info("Accessed AI Agent Playground page.")

logger.debug("Application rerun complete.")
```